server:
  port: 4009

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service-route
          uri: http://patient-service:8080
          predicates:
            - Path=/api/Patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: api-docs-patients-routes
          uri: http://patient-service:8080
          predicates:
            - Path=/api-docs/Patients
          filters:
            - RewritePath=/api-docs/Patients,/v3/api-docs

        - id: api-docs-auth-routes
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs